theme = "dark_plus"
[editor]
auto-completion = true
auto-format = true
auto-info = true
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1
cursorcolumn = true
cursorline = true
default-line-ending = "native"
end-of-line-diagnostics = "hint"
idle-timeout = 250
indent-heuristic = "simple"
line-number = "absolute"
popup-border = "all"
preview-completion-insert = true
true-color = true

[editor.auto-save]
focus-lost = true
[editor.auto-save.after-delay]
enable = true
timeout = 3000

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "│"
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true
display-messages = true
display-progress-messages = true
enable = true

[editor.smart-tab]
enable = true

[editor.statusline]
center = ["file-name"]
left = ["mode", "spinner"]
right = [
    "diagnostics",
    "selections",
    "position",
    "file-encoding",
    "file-line-ending",
    "file-type",
]
separator = "│"

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"

[editor.whitespace]
render = "all"

[keys.normal]
A-r = [":reload-all", ":lsp-restart"]
A-z = ":toggle-option soft-wrap.enable"
C-q = ":buffer-close"
f = ":format"
w = ":u"

[keys.select]
